### ISSUE TITLE
Cannot Download Target Preview Image on Site

### ISSUE THREAD

**Issue by Verbosi7y** [jaseg/gerbolyze#10]
Hi, I'm trying to download the top and bottom image but I'm getting an Internal Server Error.

**Comment by dsalychev** [comment]
Have you tried to run the script locally? It used to work well for me.

**Comment by Verbosi7y** [comment]
Ok I've tried running it locally and I'm getting an extension error since I'm missing a file with .gko|.gm1|-Edge_cuts.gbr|-Edge.Cuts.gbr|.gmb but all of my file are missing the suffixes with the default filename from EagleCAD.

**Comment by Verbosi7y** [comment]
Solved, used different CAM file.
