### ISSUE TITLE
Loss of one vertex in each element when converting in KLayout

### ISSUE THREAD

**Issue by mx-yah** [jaseg/gerbolyze#12]
Prepared Gerber from SVG 
svg-flatten --format gerber in.svg outfile.gbr

And imported outfile.gbr  in KLayout, in KLayout wiely that each element disappeared one vertex.
With gerbera files received in other ways such an error is not selected.

I did not find a way to invert svg

**Comment by neinseg** [comment]
Can reproduce. Test input and output attached.
[test data issue 12.zip](https://github.com/jaseg/gerbolyze/files/6173314/test.data.issue.12.zip)

Klayout screenshot:
![klayout_gerbolyze_issue_12](https://user-images.githubusercontent.com/67436430/111825805-32bd7780-88e8-11eb-829b-1aec4dc22c15.PNG)

**Comment by neinseg** [comment]
Okay, this is clearly a bug in KLayout.

gEDA gerbv, KiCAD gerbview **and Ucamco's reference gerber viewer** all produce correct output. I'll see whether I can raise an issue with KLayout's upstream.

[Ucamco's reference gerber viewer](https://gerber-viewer.ucamco.com/):
![ucamco_gerbolyze_issue_12](https://user-images.githubusercontent.com/67436430/111826417-f3435b00-88e8-11eb-990d-c42b42b14603.png)

gEDA gerbv:
![geda_gerbv_gerbolyze_issue_12](https://user-images.githubusercontent.com/67436430/111826446-f9393c00-88e8-11eb-852c-7b12ee70646e.png)

KiCAD gerbview:
![kicad_gerbview_gerbolyze_issue_12](https://user-images.githubusercontent.com/67436430/111826464-fe968680-88e8-11eb-8c3f-e82dfebdad01.png)

**Comment by neinseg** [comment]
Closing this, raised an issue with KLayout.
Thank you for the report!
