### ISSUE TITLE
unbuntu installation keeps telling me that the server certification verification failed

### ISSUE THREAD

**Issue by zikaden** [jaseg/gerbolyze#24]
Hi, 
I wanted to install via ubuntu but the input

pip3 install --user git+https://git.jaseg.de/pcb-tools-extension.git

results in the message server certificate verification failed, not sure why
Any help would be appreciated,
Best,
J.

Update: just solved it. Anyone else having the same issue, just run the line
git config --global http.sslVerify false

**Comment by jaseg** [comment]
This is fixed now with gerbolyze v3.0. Gerbolyze can now be installed via pip from PyPI as a normal python package, without any ugly hacks necessary anymore. All dependencies are also installed from PyPI now, so that gerbolyze does not require any host utilities anymore.
