### ISSUE TITLE
Minor issue: Git clone doesn't point to a branch

### ISSUE THREAD

**Issue by puterboy** [jaseg/gerbolyze#36]
Running the suggested command:
```git clone --recurse-submodules https://git.jaseg.de/gerbolyze.git```
gives the following error:
```warning: remote HEAD refers to nonexistent ref, unable to checkout.```

Workaround is to run:
```git branch -a```
and then `checkout` one of the branches, e.g.,
```git checkout main```

Suggest either this is "fixed" or noted in the documentation.

**Comment by jaseg** [comment]
Thanks, I forgot to set the remote HEAD ref after renaming the main branch on git.jaseg.de. It's fixed now.
