### ISSUE TITLE
How do you increase resolution of included images

### ISSUE THREAD

**Issue by puterboy** [jaseg/gerbolyze#39]
I used Inkscape to add a high resolution JPEG photo to the bottom silkscreen layer.
I tried both with the original 9MB color image and separately with a 17MB B&W dithered version of the same image.
The resulting SVG templates output by Inkscape ended up being 14MB and 23MB respectively -- so the resolution was captured by Inkscape.

In both cases, the resulting Gerber file showed only a very low resolution image (though still a little higher than the native image import tool in EasyEDA). Note that the Gerber zip file increased by only about 1.5MB.

(Interestingly, when I used Inkscape to crop the same image and then resized the smaller cropped image to the same size as the original, the resolution of the Gerber image was even worse with larger 'circles')

I am using the default settings (and thus presumably the default vectorizer) in 'gerbolyze paste'.
 
Is there any way to increase the resolution?
(e.g., setting the minimum size of the poisson discs/squares/hex etc)
It would seem that the silkscreen layer should handle finer resolutions -- after all it prints tiny letters and thin lines.

**Comment by jaseg** [comment]
You can set the smallest feature size that will be generated by passing the `--trace-space` command line option. The default value is `0.1` (mm), and you can make things finer using smaller values. Be a bit careful though, and decrease the value slowly, since the number of primitives in the Gerber file and the file's size escalate rather quickly. The default is set conservatively to work even with crappy silkscreen processes.

If you want to dither the image yourself, you can either vectorize the dithered image using Inkscape's vectorizer and use gerbolyze just for conversion, or you can pass `--vectorizer binary-contours`, which is meant to trace already dithered input images straight to gerber.

**Comment by puterboy** [comment]
> You can set the smallest feature size that will be generated by passing the `--trace-space` command line option. The default value is `0.1` (mm), and you can make things finer using smaller values. Be a bit careful though, and decrease the value slowly, since the number of primitives in the Gerber file and the file's size escalate rather quickly. The default is set conservatively to work even with crappy silkscreen processes.
> 
Do you have any idea what might be the minimum size that would work with low-end pcb companies like jlcpcb and pcbway?
Or even a guess :)

> If you want to dither the image yourself, you can either vectorize the dithered image using Inkscape's vectorizer and use gerbolyze just for conversion, or you can pass `--vectorizer binary-contours`, which is meant to trace already dithered input images straight to gerber.

How does "gerbolyze paste" then know what layer to add the vectorized image and where in the layer (what x,y position to start or even what scale -- or does it assume the image takes up the whole layer?

My dithered image is very fine so that it looks grayscale even. Will that end up creating vectorized images that are too fine?
Specifically, is there a range of "ideal" dithering resolutions that work well?

**Comment by jaseg** [comment]
> Do you have any idea what might be the minimum size that would work with low-end pcb companies like jlcpcb and pcbway?
I really don't, two reasons:

* Every service treats violations differently. Some will complain to you via email and still do a great job, others will just silently delete half the file and deliver garbage.
* Even within one service, depending on which options you choose (2 layer, 4 layer, color, ENIG plating, etc.) you may end up with a totally different silkscreen process. Generally, the more expensive boards end up with high-quality photoimaged silkscreen which can easily resolve details smaller than 0.1mm. However, less expensive boards often end up with direct-to-pcb inkjet stuff which has trouble even with 0.2mm lines.
