### ISSUE TITLE
USVG_OPTIONS='--keep-named-groups' required

### ISSUE THREAD

**Issue by deshipu** [jaseg/gerbolyze#40]
I'm trying to use this tool, but I have to yet succeed once. So far I managed to find one problem: usvg seems to be removing all groups from the svg file, unless we tell it not to with the `--keep-named-groups` option. Simply adding `USVG_OPTIONS='--keep-named-groups'` before the gerbolyze command does that, and gets rid of the `Corresponding overlay layer not found. Skipping.` errors.

I'm still getting empty output, though, so there must be more bugs to find.

**Comment by jaseg** [comment]
Thank you for the report. There was some API breakage with usvg between the last few versions. Make sure you either have an up-to-date usvg, or use the webassembly usvg build distributed in the [resvg-wasi PyPI package](https://pypi.org/project/resvg-wasi/), and an up-to-date gerbolyze and it should work now.
