### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by Wulfsta** [jaseg/gerbolyze#51]
@jaseg could you please bump the version? I see there were some commits, and assume there should be a new tag. I [rely on tags](https://github.com/NixOS/nixpkgs/blob/6083c9e1ff258d1ccd6c7f96a4ab16f0ac8dcbeb/pkgs/by-name/ge/gerbolyze/package.nix#L92) here and in Gerbonara to autoupdate these packages downstream in NixOS.

If you are planning to update without release tags, I can also switch to tracking this in an unstable fashion, and just use the latest commit.

**Comment by jaseg** [comment]
Hi there,

I'll put out a new release soon-ish. I just got stuck mid-work because of some IRL distractions, and the new changes aren't tested properly yet :)

**Comment by Wulfsta** [comment]
My apologies for the incorrect assumption then!

**Comment by jaseg** [comment]
no problem :)
